### ISSUE TITLE
Authentication errors using pyzotero

### ISSUE THREAD

**Issue by retorquere** [urschrei/pyzotero#102]
# General
Platform:  MacOS Mojave
Python version:  3.7
Pyzotero version: 1.4.4

# Problem description

I'm running the sample from the README:

```
from pyzotero import zotero
zot = zotero.Zotero(library_id, 'user', api_key)
items = zot.top(limit=5)
# we've retrieved the latest five top-level items in our library
# we can print each item's item type and ID
for item in items:
    print('Item: %s | Key: %s' % (item['data']['itemType'], item['data']['key']))
```

I got the `library_id` from [here](https://www.zotero.org/settings/keys) as per the README (the user ID) and create a new key [here](https://www.zotero.org/settings/keys/new) with all permissions.

# If possible, paste the full traceback in a code block below, and fill in the summary
<details>
    <summary>Traceback</summary>   

    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/pyzotero/zotero.py", line 426, in _retrieve_data
        self.request.raise_for_status()
      File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.zotero.org/users/1535871/items/top?limit=5&format=json

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "tt.py", line 3, in <module>
        items = zot.top(limit=5)
      File "/usr/local/lib/python3.7/site-packages/pyzotero/zotero.py", line 193, in wrapped_f
        retrieved = self._retrieve_data(func(self, *args))
      File "/usr/local/lib/python3.7/site-packages/pyzotero/zotero.py", line 428, in _retrieve_data
        error_handler(self, self.request)
      File "/usr/local/lib/python3.7/site-packages/pyzotero/zotero.py", line 1635, in error_handler
        raise error_codes.get(req.status_code)(err_msg(req))
    pyzotero.zotero_errors.UserNotAuthorised:
    Code: 403
    URL: https://api.zotero.org/users/1535871/items/top?limit=5&format=json
    Method: GET
    Response: Forbidden
</details>

**Comment by retorquere** [comment]
using

```
curl -H "Zotero-API-Version: 3" -H "Zotero-API-Key: the-api-key" "https://api.zotero.org/users/1535871/items/top?limit=5&format=json"
```

does work

**Comment by retorquere** [comment]
as does

```
curl -H "Zotero-API-Version: 3" -H "Authorization: Bearer the-api-key" "https://api.zotero.org/users/1535871/items/top?limit=5&format=json"
```

**Comment by retorquere** [comment]
To boil it down further: it looks like there's something odd going on in `requests`:

```
import os
  
api_key = os.environ['ZOTERO_API_KEY']
user_id = os.environ['ZOTERO_USER_ID']

url = f'https://api.zotero.org/users/{user_id}/items/top?limit=5&format=json'
headers = {'User-Agent': 'Pyzotero/1.4.4', 'Zotero-API-Version': '3', 'Authorization': f'Bearer {api_key}' }

# this succeeds
curl_headers = ' '.join([f'-H "{k}: {v}"' for k, v in headers.items()])
os.system(f'curl {curl_headers} "{url}"')
print('')

# this gets a 403 response
import requests
request = requests.get(
  url=url,
  headers=headers
)
print(request)

# this gets a 200 response
import urllib.request
req = urllib.request.Request(url)
for k, v in headers.items():
  req.add_header(k, v)
r = urllib.request.urlopen(req)
print(r.getcode())
```

**Comment by retorquere** [comment]
Further check: this script works on Ubuntu 19.04, so it looks like it's a problem in the requests library that's specific to MacOS.

**Comment by urschrei** [comment]
Hmm. I can't replicate this on High Sierra using Python 3.7.3 and Requests 2.22.0. What Requests version are you using?

**Comment by retorquere** [comment]
2.20.1 (see also https://github.com/psf/requests/issues/5158)

**Comment by urschrei** [comment]
Ah, OK. I've bumped the minimum version to 2.21.0 for v1.4.6.

**Comment by retorquere** [comment]
Doesn't help for me. `python3 -m requests.help` now shows

```
{
  "chardet": {
    "version": "3.0.4"
  },
  "cryptography": {
    "version": "2.7"
  },
  "idna": {
    "version": "2.7"
  },
  "implementation": {
    "name": "CPython",
    "version": "3.7.3"
  },
  "platform": {
    "release": "18.7.0",
    "system": "Darwin"
  },
  "pyOpenSSL": {
    "openssl_version": "1010103f",
    "version": "19.0.0"
  },
  "requests": {
    "version": "2.22.0"
  },
  "system_ssl": {
    "version": "1000213f"
  },
  "urllib3": {
    "version": "1.25.3"
  },
  "using_pyopenssl": true
}
```

but requests still gets me 403 errors. So it looks like it's a Mojave thing.

**Comment by urschrei** [comment]
Ugh. I wonder whether it's an SSL issue, although I'm just guessing at this point.

**Comment by retorquere** [comment]
That's what I was thinking initially but the call to `key_info` succeeds without errors.

**Comment by urschrei** [comment]
>the call to key_info succeeds without errors.

That's _very_ confusing.

**Comment by retorquere** [comment]
Yeah I don't know what to make of this at all.

**Comment by urschrei** [comment]
If you:

    import logging
    logging.basicConfig(level=logging.DEBUG)

_after_ importing requests, do you see anything interesting when a call fails?

**Comment by retorquere** [comment]
The current script is now

```
import os

import requests
import logging
logging.basicConfig(level=logging.DEBUG)

import urllib.request

api_key = os.environ['ZOTERO_API_KEY']
user_id = os.environ['ZOTERO_USER_ID']

urls = [
  f'https://api.zotero.org/users/{user_id}/items/top?limit=5&format=json',
  f'https://api.zotero.org/keys/{api_key}',
]
headers = {'User-Agent': 'Pyzotero/1.4.4', 'Zotero-API-Version': '3', 'Authorization': f'Bearer {api_key}' }

for url in urls:
  print(url)
  # this gets a 403 response
  request = requests.get(
    url=url,
    headers=headers
  )
  print(request)

  # this gets a 200 response
  req = urllib.request.Request(url)
  for k, v in headers.items():
    req.add_header(k, v)
  r = urllib.request.urlopen(req)
  print(r.getcode())
```

which gets me

```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.zotero.org:443
DEBUG:urllib3.connectionpool:https://api.zotero.org:443 "GET /users/1535871/items/top?limit=5&format=json HTTP/1.1" 403 9
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.zotero.org:443
DEBUG:urllib3.connectionpool:https://api.zotero.org:443 "GET /keys/APIKEY HTTP/1.1" 200 182
https://api.zotero.org/users/1535871/items/top?limit=5&format=json
<Response [403]>
200
https://api.zotero.org/keys/APIKEY
<Response [200]>
200
```

**Comment by urschrei** [comment]
OK, so nothing particularly useful there. Bah.

**Comment by urschrei** [comment]
Closing this, as it's not really a Pyzotero error.
