### ISSUE TITLE
Zotero addCitation from pyzotero

### ISSUE THREAD

**Issue by Dan-Kechik** [urschrei/pyzotero#103]
Hello.

Is it possible to call zotero "addCitation" method using pyzotero? It's too convenient elements selecting method in zotero word plugin as it's seen on picture below. Can I call this window and get chosen elements data?

![Needed result looking like this](https://user-images.githubusercontent.com/20151051/63648665-baa6c400-c73b-11e9-911e-84b4b4f1f409.png)

Thank you for your attention.

**Comment by urschrei** [comment]
Hi Dan,
I'm not sure what you're asking, but pyzotero doesn't interact with your local zotero instance or Word plugin in any way. Sorry!
