### ISSUE TITLE
everything doesn't persist "since" query item across requests

### ISSUE THREAD

**Issue by paregorios** [urschrei/pyzotero#104]
# General
Platform:  OSX
Python version:  3.7.4
Pyzotero version: 1.4.6

# Problem description
- What were you trying to do? use the new ```everything()``` method to get top-level items since a particular version
    - What API call did it involve: ```zot.everything(zot.top(since=version))```
    - What error was raised? None, but the "since" attribute seems only to have been applied to the first paged call, instead of all of them (see debug output below).

# If possible, paste the full traceback in a code block below, and fill in the summary
<details>
    <summary>Debug logging</summary>
    
    DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.zotero.org:443
    DEBUG:urllib3.connectionpool:https://api.zotero.org:443 "GET /groups/2533/items/top?since=10000&format=json&limit=100 HTTP/1.1" 200 40653
    DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.zotero.org:443
    DEBUG:urllib3.connectionpool:https://api.zotero.org:443 "GET /groups/2533/items/top?limit=100&start=100 HTTP/1.1" 200 40649
    DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.zotero.org:443
    DEBUG:urllib3.connectionpool:https://api.zotero.org:443 "GET /groups/2533/items/top?limit=100&start=200 HTTP/1.1" 200 36648
    DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.zotero.org:443
    DEBUG:urllib3.connectionpool:https://api.zotero.org:443 "GET /groups/2533/items/top?limit=100&start=300 HTTP/1.1" 200 41131
    DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.zotero.org:443
    DEBUG:urllib3.connectionpool:https://api.zotero.org:443 "GET /groups/2533/items/top?limit=100&start=400 HTTP/1.1" 200 31584
    DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.zotero.org:443
    DEBUG:urllib3.connectionpool:https://api.zotero.org:443 "GET /groups/2533/items/top?limit=100&start=500 HTTP/1.1" 200 35509
    DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.zotero.org:443
    DEBUG:urllib3.connectionpool:https://api.zotero.org:443 "GET /groups/2533/items/top?limit=100&start=600 HTTP/1.1" 200 28451
    DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.zotero.org:443
    DEBUG:urllib3.connectionpool:https://api.zotero.org:443 "GET /groups/2533/items/top?limit=100&start=700 HTTP/1.1" 200 27701
    DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.zotero.org:443
    DEBUG:urllib3.connectionpool:https://api.zotero.org:443 "GET /groups/2533/items/top?limit=100&start=800 HTTP/1.1" 200 30169
    DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.zotero.org:443
    DEBUG:urllib3.connectionpool:https://api.zotero.org:443 "GET /groups/2533/items/top?limit=100&start=900 HTTP/1.1" 200 25418
    DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.zotero.org:443

</details>

**Comment by urschrei** [comment]
Oh, that's not right. I'll take a look!

**Comment by urschrei** [comment]
It was an error on the Zotero API side, [now fixed](https://groups.google.com/d/msg/zotero-dev/iiIjMGv_duE/AM8P5H0GCQAJ)!

**Comment by paregorios** [comment]
Confirmed. Now works for me. Thanks.
