### ISSUE TITLE
Error in docs of create_collections(): parentCollection instead of parent

### ISSUE THREAD

**Issue by fabbra** [urschrei/pyzotero#113]
Creating a subcollection as described in [the docs](https://pyzotero.readthedocs.io/en/latest/#zotero.Zotero.create_collections) fails with the following error message:

> 'code': 400, 'message': "'parent' property is now 'parentCollection'"

In the dict passed as the first input parameter to create_collections() one must use the key `parentCollection` and not `parent`.

I guess the docs should be updated accordingly.

Code example that fails:
```
zot = zotero.Zotero(library_id, library_type, api_key)
result = zot.create_collections([{'parent': parent_id, 'name': 'test'}])
```
Code example that runs successfully:
```
zot = zotero.Zotero(library_id, library_type, api_key)
result = zot.create_collections([{'parentCollection': parent_id, 'name': 'test'}])
```

**Comment by urschrei** [comment]
Thanks!
