### ISSUE TITLE
assessing all attachments of items with multiple attachments

### ISSUE THREAD

**Issue by fabbra** [urschrei/pyzotero#114]
# General
If at all possible, provide a [MVCE](https://stackoverflow.com/help/minimal-reproducible-example). If this is inappropriate (e.g. it's obviously a bug), just fill in the below:

Platform:  Win64, Windows10
Python version:  3.7.7
Pyzotero version: 1.4.15

# Problem description
In view of renaming attachments I'm trying to access all attachments of my Zotero library items.
However, for **items with more than one attachment** I can only determine one single attachment when trying to get their information via `item['links']['attachment']['href']`.

I've used the following example on my test database...
```
zot = zotero.Zotero(library_id, library_type, api_key)
for i in zot.items():
    if 'parentItem' in i['data']:
        parent = i['data']['parentItem']
    else:
        parent = ''
    if 'attachment' in i['links']:
        attachment = i['links']['attachment']['href'].split('/')[-1]
    else:
        attachment = ''
    print('key={:s} [type={:s}]: attachment={:s}; parent={:s}'.format(i['key'], i['data']['itemType'], attachment, parent))      
```

And get the following result:

> key=9C8WQAQY [type=attachment]: attachment=; parent=SET9X4NF
> key=DATCD5PW [type=attachment]: attachment=; parent=**48342843**
> key=72PP5P6X [type=attachment]: attachment=; parent=SET9X4NF
> key=3373DDZK [type=attachment]: attachment=; parent=**48342843**
> key=6ZQ8G954 [type=note]: attachment=; parent=48342843
> key=QM946GHZ [type=conferencePaper]: attachment=; parent=
> key=ZTNPW922 [type=conferencePaper]: attachment=; parent=
> key=SET9X4NF [type=conferencePaper]: attachment=9C8WQAQY; parent=
> key=**48342843** [type=conferencePaper]: attachment=3373DDZK; parent=

As example, item `48342843` has two attachments (`DATCD5PW ` and `3373DDZK`) but only one `3373DDZK` is available via `item['links']['attachment']['href']`. The same goes for `SET9X4NF` with attachments `9C8WQAQY` and `72PP5P6X`.

The only way I currently see to find all attachments of an item is to get **all** items in my library, go through all of which are of `itemType` attachment and look for their `parentItem`.
However, is there no other solution which is more efficient?

In the hope that this is a pyzotero- and not Zotero-specific question I thank you in advance for your reply.

**Comment by urschrei** [comment]
Unless I'm misunderstanding you, you would need to do the following:

create an empty `updated` list
1. retrieve all top-level items for your library / collection / subcollection
2. for each item, check whether it has children by checking the `['meta']['numChildren']` key
3. If there are children, retrieve them by calling `zot.children(parentid)`
4. For each child, check whether it is an attachment by checking `['data']['itemType']`
5. If it _is_ an attachment, rename it and append to `updated`

Once you're finished, write the contents of `updated` back to the API using `update_items()`. Remember that you can only update 50 items per lcall, so you should probably call it in a loop using sequential chunks of 50 items from `updated`.

**Comment by fabbra** [comment]
This is EXACTLY what I need. I was missing the `zot.children()`. Thanks a lot!

**Comment by fabbra** [comment]
By the way: I had forseen to perform `update_items()` item-by-item but this might be not that efficient, right?

**Comment by urschrei** [comment]
You should definitely append updated items to a new list, and use that (in chunks of 50) with `update_items()` once you've finished the renaming operation. Otherwise it's potentially 50x as many API calls!

**Comment by fabbra** [comment]
Thanks!

**Comment by fabbra** [comment]
One more question relating the performance, isn't there a way of calling `zot.children(parentid)` (or a related function) to get the children for multiple items at once? 
I've observed that doing this for a large library item-by-item takes quite some time and I would like to iterate through all my library items to check the filenames of all my attachments.

**Comment by urschrei** [comment]
No, unfortunately the Zotero API only has a single method, and it's one item at a time.

**Comment by fabbra** [comment]
One more question on this topic:
The header of `addto_collection()` says that it can add ["one or more items to a collection"](https://github.com/urschrei/pyzotero/blob/master/pyzotero/zotero.py#L1476).
However, when passing a list of multiple items to the function it fails.

Is this:
a) not supported by this function (and the header is wrong) or 
b) passing a list of items is not the right way to pass multiple items to this function?

**Comment by urschrei** [comment]
No, it's a typo; the header is wrong. If you want to add multiple items to a collection at once, modify each item's `collections` key by appending the new collection key, then passing the list of modified items to [`update_items()`](https://pyzotero.readthedocs.io/en/latest/#zotero.Zotero.update_items).

**Comment by fabbra** [comment]
> No, unfortunately the Zotero API only has a single method, and it's one item at a time.

Unfortunately I am running into more and more timing issues with the `zot.children()` method.

I was wondering whether there was a simple way of parallelizing these requests?
Even if the API does only support one item at a time, could we request to get the children of multiple (e.g., 100) items in parallel?

**Comment by urschrei** [comment]
You can certainly spin up a multiprocessing pool and see if that works for chunks of renames at a time, but I haven't tried it myself – you may run into rate-limiting issues (although Pyzotero will respect a backoff instruction from the API)

**Comment by fabbra** [comment]
Using the `parfor` package I get a speedup of about 6x for getting the children of 522 items (62 vs 385 seconds). Not perfect but already much better than before 👍
