### ISSUE TITLE
attachment_simple() fail

### ISSUE THREAD

**Issue by theofech** [urschrei/pyzotero#121]
Hello,

I have a matter with the attachment_simple() method that only return me "failure". 

Is it due to the beta version ?
If not, is there somewhere a documentation to understand what is the cause of this kind of return ?

Thanks you very much,

Theodore

# General
If at all possible, provide a [MVCE](https://stackoverflow.com/help/minimal-reproducible-example). If this is inappropriate (e.g. it's obviously a bug), just fill in the below:

Platform:  
Python version:  3.8
Pyzotero version:  1.4.15

# Problem description
- What were you trying to do?
I try to send a html file to my online library.

    - What API call did it involve
zot.attachment_simple(["D:\\Téléchargement\\fichier.html"],zot.item("FU5XMJVZ"))

    - What error was raised?

I receive a dico with only "failure": "FU5XMJVZ" , and I constat that there is nothing on my online library.

<details>
    <summary>Traceback</summary>
    
    {'success': [], 'failure': [{'itemType': 'attachment', 'linkMode': 'imported_file', 'title': 'fichier.html', 'accessDate': '', 'note': '', 'tags': [], 'collections': [], 'relations': {}, 'contentType': '', 'charset': '', 'filename': 'D:\\Téléchargement\\fichier.html', 'md5': None, 'mtime': None, 'parentItem': {'key': 'FU5XMJVZ', 'version': 150731, 'library': {'type': 'user', 'id': 2269526, 'name': 'Impact_matters', 'links': {'alternate': {'href': 'https://www.zotero.org/impact_matters', 'type': 'text/html'}}}, 'links': {'self': {'href': 'https://api.zotero.org/users/2269526/items/FU5XMJVZ', 'type': 'application/json'}, 'alternate': {'href': 'https://www.zotero.org/impact_matters/items/FU5XMJVZ', 'type': 'text/html'}}, 'meta': {'parsedDate': '2020', 'numChildren': 0}, 'data': {'key': 'FU5XMJVZ', 'version': 150731, 'itemType': 'webpage', 'title': 'Lundi Carotte', 'creators': [], 'abstractNote': '', 'websiteTitle': '', 'websiteType': '', 'date': '2020', 'shortTitle': '', 'url': 'https://www.lundicarotte.fr', 'accessDate': '', 'language': '', 'rights': '', 'extra': '', 'deleted': 1, 'tags': [], 'collections': ['TA9F4UHW'], 'relations': {}, 'dateAdded': '2020-09-30T15:29:42Z', 'dateModified': '2020-09-30T15:29:42Z'}}}], 'unchanged': []}

</details>

**Comment by urschrei** [comment]
Try `zot.attachment_simple(["D:\Téléchargement\fichier.html"], "FU5XMJVZ")`.

**Comment by theofech** [comment]
Thanks for your help.
That's working : Alleluja !
