### ISSUE TITLE
Add an Article by Its DOI Number?

### ISSUE THREAD

**Issue by Alyetama** [urschrei/pyzotero#122]
Platform:  MacOS
Python version:  3.7
Pyzotero version: 5.0.91

Is there a way to dd article by its DOI number without specifying all the other fields manually (the same way "add item by identifier" button does)?   I would appreciate any thoughts/suggestions.

Thank you!

**Comment by Alyetama** [comment]
Solved!

**Comment by urschrei** [comment]
No, as this isn't supported by the Zotero API.
