### ISSUE TITLE
No attribute ‘_FeedParserMixin’?

### ISSUE THREAD

**Issue by Michael-N-N** [urschrei/pyzotero#126]
Hello

I recently updated some Python package including pyzotero (1.4.20) and feedparser (6.0.2). Now I get an error message when loading pyzotero stating that feedparser has no attribute ‘_FeedParserMixin’?
Any help is highly appreciated.

Best wishes
Michael

**Comment by urschrei** [comment]
Pyzotero currently requires (and installs) a Feedparser version less than 6. If you've installed a more recent version of Feedparser separately, it will conflict.

**Comment by Michael-N-N** [comment]
Thanks! A downgrade to feedparser 5.2.1 solved the problem.
