### ISSUE TITLE
Question about items retrieval methods

### ISSUE THREAD

**Issue by malbahrani** [urschrei/pyzotero#127]
Platform:  Windows 10
Python version:  3.7.3 
Pyzotero version: 1.4.20

Hi
I am just wondering what is the difference between using `Zotero.items()` versus `Zotero.top()`?  I have 65 items in my library, and when I use the `items()` method I get 100 items.

**Comment by urschrei** [comment]
The difference is explained in the docs. If you're unsure about the structure of Zotero library items, the forums are probably a good place to ask.

**Comment by malbahrani** [comment]
Thanks.  I checked Zotero API docs, and I found details about how the Zotero library is categorized.  This is the link: https://www.zotero.org/support/dev/web_api/v3/basics
