### ISSUE TITLE
can't delete tags

### ISSUE THREAD

**Issue by clsnyder** [urschrei/pyzotero#128]
# General

Platform:  
Python version:  
Pyzotero version: installed today?

# Problem description
I can access all my tags easily, but in 
Trying to delete tags from my unshared library - even with a single tag, I get:

**UserNotAuthorised: 
Code: 403
URL: https://api.zotero.org/users/18471/tags?tag=hyponatremia
Method: DELETE
Response: Write access denied**

A code example:
```
from pyzotero import zotero
zot = zotero.Zotero('18471', 'user', 'API#')
all_tags = zot.everything(zot.tags())
#create a first subset of this list
tags_part1 = all_tags[:50]
#delete first 50 tags
zot.delete_tags(*tags_part1)
```

# If possible, paste the full traceback in a code block below, and fill in the summary
<details>

</details>

**Comment by urschrei** [comment]
The only thing I can think of is that your API key doesn't have write access for the library you're trying to edit. Can you go to https://www.zotero.org/settings/keys and check that the key you're using has all the permissions? If you select 'edit key', you can then verify that it has write access for your personal library and whatever groups you're trying to access.

**Comment by clsnyder** [comment]
Thanks I will check that.

**Comment by clsnyder** [comment]
Hi Stephan

I'm sorry I was too dim to check the permissions in the first place. Once I
added write permissions, it worked perfectly.!

Thanks again for your help.

Charles

BTW, was in Dublin a few yrs ago - great city! Looking forward to going
(anywhere) again....

**Comment by urschrei** [comment]
Great, glad it's working!
