### ISSUE TITLE
There has an question of this code

### ISSUE THREAD

**Issue by xingziyangxyz** [urschrei/pyzotero#133]
I used follow code read doc list in my zotero, there is 27 items in collection "04", but the output of code is 76. I con not understand why?

zot = zotero.Zotero(library_id, library_type, api_key ,locale="zh-CN")
colls = zot.collections()
for coll in colls:
    if coll['data']['name'] == '04':
        key=coll['key']
        break
pyz = zot.everything(zot.collection_items(key))
print(len(pyz))

**Comment by urschrei** [comment]
I assume you need top-level items: `https://pyzotero.readthedocs.io/en/latest/index.html?highlight=collection_items#zotero.Zotero.collection_items_top`
