### ISSUE TITLE
update_items() only processes the first chunk (50 items)

### ISSUE THREAD

**Issue by fabbra** [urschrei/pyzotero#137]
Isn't there an indentation error (one tab too much) here?

https://github.com/urschrei/pyzotero/blob/fe9cd007a0216350fae405a98885c22d9308ad27/pyzotero/zotero.py#L1448

and also here:

https://github.com/urschrei/pyzotero/blob/fe9cd007a0216350fae405a98885c22d9308ad27/pyzotero/zotero.py#L1478

I've discovered that `update_items()` only updates the first chunk (i.e., the first 50 items) and all the remaining items do not get updated.

**Comment by urschrei** [comment]
Hmm. Looks like it. I won't be able to fix it til Saturday, however.

**Comment by urschrei** [comment]
Released to PyPI as 1.4.23
