### ISSUE TITLE
How to get notes associated with a journal entry?

### ISSUE THREAD

**Issue by lpjiang97** [urschrei/pyzotero#138]
I'm trying to access the note entries that are associated with journal entries. But I'm having a hard time locating that. The dict returned by `api.items()` does not seem to contain note entries (tags do exist). I have tried the following code:
```
myapi.everything(myapi.items(itemType='Note'))
```
But this returns an empty list while I have multiple notes associated with `journalArticle` types. My private key has "Allow note access" turned on.

I'm on version `1.4.22`, macOS Big Sur, and Python 3.8. Any help is appreciated!

**Comment by urschrei** [comment]
Note is an item type, and in your case it will be a child (or children) of a top-level journalArticle item. One way to do it would be to retrieve all top-level items first, and then call .children(itemType="Note") on each item that has a child count (and any other criteria you want to restrict by).

**Comment by lpjiang97** [comment]
Gotcha, works now. Thanks!
