### ISSUE TITLE
Feature Request - Add tags and modify comments of annotations

### ISSUE THREAD

**Issue by Mjvolk3** [urschrei/pyzotero#154]
Currently the `Zotero.add_tags()` only works for metadata tags, but it would be convenient to modify tags and even update comments of annotations. It wouldn't make much sense to modify the other items of the annotation dict, maybe annotation color. My use case is to connect Zotero notes to Dendron a note taking tool in VsCode. After importing notes to Dendron, I would like to be able to modify them there, and write the changes back to Zotero. This would be possible with the requested feature. Thanks for your consideration.

**Comment by urschrei** [comment]
This isn't currently supported by the Zotero API. See https://github.com/urschrei/pyzotero/issues/148

**Comment by Mjvolk3** [comment]
Thanks for your speedy response! From what I saw it looks like the issue is that they haven't documented it yet.

**Comment by urschrei** [comment]
Hmm. I'll have to think about what the API looks like, and I'm hesitant to add public API methods for undocumented features. 

In the mean time, v1.5.3 (just released to pypi) now supports annotation fields, so you can modify annotation items (retrieved as per #148), by altering their `['data']['annotationComment']` and `['data']['tags']` keys, then write the changes to your library using `update_item(modified_item)`. I just tried this and the changes appear exactly as you would expect.

**Comment by urschrei** [comment]
🤦‍♂️ I left out `annotationText`. I've just pushed 1.5.4 to pypi – try that? (sorry!)

**Comment by Mjvolk3** [comment]
Works perfectly now. Thank you!

**Comment by urschrei** [comment]
@EricThrift Oops. Just published 1.5.5 with a fix.
