### ISSUE TITLE
Moving Collections from my library to group library

### ISSUE THREAD

**Issue by JorrisonFord** [urschrei/pyzotero#161]
Hey urschrei,

Thank you again for your help! 
After completing my comparison of the two reviewers, I am trying to transfer a collection from my private library to a group library. Is there an option for that? I created two Zotero objects, but I am not sure if they are able to communicate. Retrieving the item's keys does not work, because they are different in the two libraries.
Any ideas on that?

**Comment by urschrei** [comment]
I don't _think_ you can transfer items between two libraries using the API, but you should ask whether it's possible on https://forums.zotero.org/discussions

**Comment by JorrisonFord** [comment]
Thank you for the fast reply!

I looked into the discussions and there is no option for transferring items between libraries except by drag-and-drop in Zotero. Then that is what I have to do. Thank you anyways.
