### ISSUE TITLE
switch to httpx as the underlying HTTP library

### ISSUE THREAD

**Issue by urschrei** [urschrei/pyzotero#169]
It seems to have more momentum than `requests`, supports HTTP/2, and supports async, should that ever become a priority. [Its API is also largely the same as `requests`](https://www.python-httpx.org/compatibility/), so it wouldn't be particularly painful.

**Comment by Ousret** [comment]
Hello there,

Sorry to barge in,
There's an alternative you may be interested in. https://github.com/jawah/niquests

This is a drop-in-worthy replacement for Requests that ships with modern capabilities and allows you a painless transition.
I can answer any concerns you may have.
