### ISSUE TITLE
Websockets / Streaming

### ISSUE THREAD

**Issue by CodeJunkie01** [urschrei/pyzotero#173]
Does the library support the topic subscription function of Zotero as described here:
https://www.zotero.org/support/dev/web_api/v3/streaming_api ?
I did read through the docs and did not find anything about it (quick read through the sourcecode did not find anything either).

If it does not is there any specific reason that it has not been implemented yet? 
Otherwise I could look into maybe adding it.

Sorry if I missed it in the docs.

**Comment by urschrei** [comment]
No, because nobody has ever asked for it. I'm certainly open to the idea, but the documentation looks incomplete (I can't see any update notifications), and it seems like a lot of work, but if you feel like it's useful to you, by all means…
