### ISSUE TITLE
The first 9 items repeat themselves 

### ISSUE THREAD

**Issue by zeynepdirier** [urschrei/pyzotero#176]
While printing items with a basic for loop & item['data'] I get the first 9 items and then the whole item list from the beginning as an output. So if I have 36 entries, I get  45. If I add any more publications to the collection, the duplicating 9 items change but the duplicating ones are still the first 9 entries. 

Example Output:

Entry-1
Entry-2
Entry-3
Entry-4
Entry-5
Entry-6
Entry-7
Entry-8
Entry-9
Entry-1
Entry-2
Entry-3
Entry-4
Entry-5
Entry-6
Entry-7
Entry-8
Entry-9
Entry-10
Entry-12

for 12 publications in total.

**Comment by urschrei** [comment]
Please post a reproducible example showing the problem.
