### ISSUE TITLE
Formatting parameters ignored when fetching items from Zotero

### ISSUE THREAD

**Issue by Smogglethorp-T-Hendlesworthington** [urschrei/pyzotero#195]
**Platform:**
- Python ver. 3.12.5
- Pyzotero ver. 1.5.27

**Problem**
Formatting parameters are ignored when fetching items from Zotero
```
from pyzotero import zotero

API_KEY =   # ...
LIBRARY_ID = # ...
LIBRARY_TYPE = # ...

library = zotero.Zotero(LIBRARY_ID, LIBRARY_TYPE, API_KEY)

print(len(library.top(format="versions"))
```
This will always give a length of 100. Further inspection shows that the call to `library.top(format="versions")` returns exactly the same thing independent of the parameters provided (or no parameters at all).

The issue isn't present on version 1.5.25—so it's due to a change made in the past few days (as of the writing of this).

**Comment by urschrei** [comment]
Yep, that's a bug. v1.5.29 (on PyPI now) should fix it.

**Comment by Smogglethorp-T-Hendlesworthington** [comment]
Yup that did it! Thank you~
