### ISSUE TITLE
Text encoding issues

### ISSUE THREAD

**Issue by smargh** [urschrei/pyzotero#30]
I have a number of items in my Zotero library that have non-ASCII characters. I do not always have properly encoded results returned from `pyzotero`. Some examples:

When I use `zot.item(item_key, content='citation', style='chicago-author-date')`, this is returned when I print using UTF8 encoding: `<span>(NoĂŤl 2011)</span>`. However, whenever I use `zot.item(item_key, content='bib', style='chicago-author-date')`, and I print using UTF8 encoding, I get:
```
<div class="csl-entry">Noël, Marie-Pierre. 2011. “Isocrates and the Rhetoric to Alexander: Meaning and Uses of Tekmerion.” <i>Rhetorica: A Journal of the History of Rhetoric</i> 29 (3) (August): 319–335.</div>
```
Clearly, it is not an issue with the data Zotero's API is giving to `pyzotero`, since one method prints properly and the other does not. There must be an encoding difference in your methods.

**Comment by sraimund** [comment]
Yes, the encoding in the requests library is guessed by chardet in case it is not included in the response (https://github.com/kennethreitz/requests/blob/master/requests/models.py#L748-749). As it is stated, that the Zotero API always returns UTF-8 (https://groups.google.com/forum/#!topic/zotero-dev/q8ZxilZobo4), you can maybe add the line `self.request.encoding = "utf-8"` in the _retrieve_data() method of zotero.py after the request is made (e.g. before line https://github.com/urschrei/pyzotero/blob/master/pyzotero/zotero.py#L269). I had a problem with umlauts in my citations and it seems to be solved by this additional line.
