### ISSUE TITLE
add item with a parent

### ISSUE THREAD

**Issue by adasilva** [urschrei/pyzotero#40]
When attaching a file usin pyzotero API, one can specify an ID for a parent,

`attachment_simple(files[, parentid])`

I'd like to also allow for 

`create_items(items)`

to have an optional parent id,

`create_items(items[, parentid])` 

Is this already included in pyzotero? If not, is it possible within zotero API?

**Comment by jdidion** [comment]
I think this is required for attaching notes as children of items (see https://www.zotero.org/support/dev/web_api/v3/write_requests about half-way down the page, under the "Both PUT and PATCH" header). When I try to create a note by manually adding the 'parentItem' property and setting it to the item ID, I get a 'circular reference detected' error.

**Comment by urschrei** [comment]
Could you try this now?
