### ISSUE TITLE
KeyError when using Zotero.make_iter

### ISSUE THREAD

**Issue by rdhyee** [urschrei/pyzotero#52]
I'm running into a `KeyError: u'self'` when using `Zotero.make_iter`, specifically on  https://github.com/urschrei/pyzotero/blob/v1.1.14/pyzotero/zotero.py#L616 (for pyzotero v 1.1.14).  I *think* the problem is related to ['self' entry missing from links · Issue #43 · urschrei/pyzotero](https://github.com/urschrei/pyzotero/issues/43). 

Here's a Jupyter notebook demonstrating the problem:

https://gist.github.com/404573708a805861edb5

In the notebook, I also write `zot.all_items` as a lazy generator of all the items.  From what I understand `zot.everything` grabs all the items on call rather than do so lazily.  (Interested in your thoughts on such an approach.)

**Comment by urschrei** [comment]
Can you pull the dev branch and try this again? I've added a workaround for the missing 'self' link…

**Comment by rdhyee** [comment]
Thanks @urschrei -- that did the trick:

I upgraded to the dev branch with

```
pip install --upgrade git+https://github.com/urschrei/pyzotero.git@dev
```

and I no longer get the exception from `Zotero.make_iter`.  

That said, I still prefer a lazy generator for all the items, which, correct me if I'm wrong, is not how `Zotero.everything()` does.

**Comment by urschrei** [comment]
Nope, .everything() gets everything all at once, so wrapping makeiter is the way to go if you want laziness.

**Comment by rdhyee** [comment]
Thanks for confirming, @urschrei.
