### ISSUE TITLE
Notes not retrieved from server

### ISSUE THREAD

**Issue by Unode** [urschrei/pyzotero#54]
Hi,

I've been trying to use pyzotero to interact with the zotero server and automate a few actions. So far this has been going fine but I seem to have hit a roadblock with notes.
Checking the documentation and the code there aren't many but a few references seem to point out that notes should also be fetched from the server.

I've tried different things including the `everything` method but the returned list/dicts doesn't contain notes (tab next to 'tags'). I do get a `note` when it is associated with a file (i.e. PDF) but not when it's associated with an item (parent of PDF and Notes - don't know the exact term).

So the question is, how do I fetch these notes?

**Comment by urschrei** [comment]
There are two ways:
- If you know what items you want to fetch notes for, you can retrieve them, then get their child items using `.children(itemID, itemType=Note)`
- If you want notes for your entire library, you can wrap `.items(itemType='Note')` in an `everything()` call, though this might take a long time / result in rate-limiting, depending on the size of your library.

In either case, the key part is filtering by `itemType`.
