### ISSUE TITLE
Output bug of everything(tags) function

### ISSUE THREAD

**Issue by z-acl** [urschrei/pyzotero#58]
Hi!
The sentence zot.everything(zot.tags()) return a list composed by string values for the first 100 items and lists (links,meta,tag) for the others.
From the doc, the awaited behavior would have been only a list of string.
Bye,
z-acl

Win 8.1 / Anaconda Python 3.5 / Pyzotero  1.1.16 installed by pip

**Comment by urschrei** [comment]
Fixed and released on PyPI as 1.1.18
