### ISSUE TITLE
Creating new item fails, gives error

### ISSUE THREAD

**Issue by rkclement** [urschrei/pyzotero#62]
Running the following code keeps giving me the error that is shown. The 400 error code appears to be indicating that writing to the library is not allowed, but this is for my personal Zotero library and I have allowed write permissions. What could be causing this error?

```
zlib = zotero.Zotero(<ID>, 'user', <API KEY>)

newitem = zlib.item_template('book')
newitem['creators'][0]['firstName'] = 'Monty'
newitem['creators'][0]['lastName'] = 'Cantsin'
newitem['title'] = 'Maris Kundzins: A Life'
newitem['relations'] = ''

resp = zlib.create_items([newitem])
```

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
/Users/[USER]/anaconda/lib/python3.5/site-packages/pyzotero/zotero.py in create_items(self, payload)
    952         try:
--> 953             req.raise_for_status()
    954         except requests.exceptions.HTTPError:

/Users/[USER]/anaconda/lib/python3.5/site-packages/requests/models.py in raise_for_status(self)
    861         if http_error_msg:
--> 862             raise HTTPError(http_error_msg, response=self)
    863 

HTTPError: 400 Client Error: Bad Request for url: https://api.zotero.org/users/[ID]/items?key=[API KEY]

During handling of the above exception, another exception occurred:

UnsupportedParams                         Traceback (most recent call last)
<ipython-input-59-b2bde453aeff> in <module>()
      4 newitem['relations'] = ''
      5 
----> 6 resp = zlib.create_items([newitem])

/Users/[USER]/anaconda/lib/python3.5/site-packages/pyzotero/zotero.py in create_items(self, payload)
    953             req.raise_for_status()
    954         except requests.exceptions.HTTPError:
--> 955             error_handler(req)
    956         return self._json_processor(feedparser.parse(data))
    957 

/Users/rclement/anaconda/lib/python3.5/site-packages/pyzotero/zotero.py in error_handler(req)
   1236                 error_handler(new_req)
   1237         else:
-> 1238             raise error_codes.get(req.status_code)(err_msg(req))
   1239     else:
   1240         raise ze.HTTPError(err_msg(req))

UnsupportedParams: 
Code: 400
URL: https://api.zotero.org/users/[ID]/items?key=[API KEY]
Method: POST
Response: Uploaded data must be a JSON array

---------------------------------------------------------------------------

**Comment by urschrei** [comment]
The problem is the `relations` key, which can't be an empty string. You don't have to specify it for object creation anyway – simply omitting it should allow you to create the item using the code above.

**Comment by rkclement** [comment]
I put in the empty string for the `relations` key, because when I pulled the item template, that field was:
` 'relations': {},`
Is that what the field should be?

Removing the specification for `relations` still gives an error:

> ---------------------------------------------------------------------------
> HTTPError                                 Traceback (most recent call last)
> /Users/rclement/anaconda/lib/python3.5/site-packages/pyzotero/zotero.py in create_items(self, payload)
>     952         try:
> --> 953             req.raise_for_status()
>     954         except requests.exceptions.HTTPError:
> 
> /Users/rclement/anaconda/lib/python3.5/site-packages/requests/models.py in raise_for_status(self)
>     861         if http_error_msg:
> --> 862             raise HTTPError(http_error_msg, response=self)
>     863 
> 
> HTTPError: 400 Client Error: Bad Request for url: https://api.zotero.org/users/[USER ID]/items?key=[API KEY]
> 
> During handling of the above exception, another exception occurred:
> 
> UnsupportedParams                         Traceback (most recent call last)
> <ipython-input-20-5bf414560835> in <module>()
>       4 
>       5 
> ----> 6 resp = zlib.create_items([newitem])
> 
> /Users/rclement/anaconda/lib/python3.5/site-packages/pyzotero/zotero.py in create_items(self, payload)
>     953             req.raise_for_status()
>     954         except requests.exceptions.HTTPError:
> --> 955             error_handler(req)
>     956         return self._json_processor(feedparser.parse(data))
>     957 
> 
> /Users/rclement/anaconda/lib/python3.5/site-packages/pyzotero/zotero.py in error_handler(req)
>    1236                 error_handler(new_req)
>    1237         else:
> -> 1238             raise error_codes.get(req.status_code)(err_msg(req))
>    1239     else:
>    1240         raise ze.HTTPError(err_msg(req))
> 
> UnsupportedParams: 
> Code: 400
> URL: https://api.zotero.org/users/[USER ID]/items?key=[API KEY]
> Method: POST
> Response: Uploaded data must be a JSON array

I have tried to change the item type and get the same error, and tried just specifying one key, e.g. just the title, and still get the same error. I can't seem to find any guidance on why, after setting one or more of the keys in the JSON array, it would now not be recognized as a JSON array.

**Comment by urschrei** [comment]
So the following code doesn't work for you? I'm just double-checking because I can't replicate the problem on Python 3.4.1

    zlib = zotero.Zotero(<ID>, 'user', <API KEY>)
    newitem = zlib.item_template('book')
    newitem['creators'][0]['firstName'] = 'Monty'
    newitem['creators'][0]['lastName'] = 'Cantsin'
    newitem['title'] = 'Maris Kundzins: A Life'
    resp = zlib.create_items([newitem])

Also, could you confirm what version of Pyzotero you're running:

    from pyzotero import zotero
    print(zotero.__version__)

It should be version 1.1.19.

**Comment by rkclement** [comment]
Aha! It was the version. I thought I had updated, but the previous update apparently didn't work. Now running 1.1.19 and the code works as it should. Thank you!
