### ISSUE TITLE
unexpected keyword argument 'payload' in update_collection and set_fulltext

### ISSUE THREAD

**Issue by andymass** [urschrei/pyzotero#68]
Using the following (from the documentation),
```python
c = zot.collections()
c[0]['name'] = 'Whither Digital Humanities?'
zot.update_collection(c[0])
```
gives,
```
TypeError: request() got an unexpected keyword argument 'payload'
```
This also happens with the new `set_fulltext` method.  Versions: Python 3.6.0, requests 2.13.0, pyzotero 1.2.1.  The cause seems to be [here](https://github.com/urschrei/pyzotero/blob/9ebe157053424240df7fb600f6fcd34af52932f6/pyzotero/zotero.py#L1078), using `payload=json.dumps(payload))`, where `requests.put` expects `data=` or `json=`.

I also noticed `Content-Type` is not being set to `application/json` in these methods- changing to `data=` may not be enough.

**Comment by urschrei** [comment]
Ugh, sorry about that. I just pushed 1.2.2 to PyPI, with fixes.
