### ISSUE TITLE
Allow bibtexparser options

### ISSUE THREAD

**Issue by MerlinB** [urschrei/pyzotero#81]
Platform: Ubuntu 16.04
Python version:  3.6.5
Pyzotero version: 1.3.2

When trying to retrieve a bibliography with `format='bibtex'` containing string-defined months, bibtexparser fails with `UndefinedString` as described in the [documentation](https://bibtexparser.readthedocs.io/en/master/tutorial.html?highlight=string#step-2-parse-it). It needs `common_strings = True` being able to be passed to bibtexparser.loads().

**Comment by urschrei** [comment]
Fixed in 1.3.3, released on PyPI.

**Comment by MerlinB** [comment]
Sorry, my comment was misleading. I created a PR.

**Comment by urschrei** [comment]
Ah. Merged and released on PyPI as 1.3.4. Thanks!
