### ISSUE TITLE
Tutorials/Examples

### ISSUE THREAD

**Issue by SR--** [urschrei/pyzotero#83]
Sorry, not a technical issue.

Is there a chance for some realistic tutorials/example beyond the very brief ones in the docs? I am new to Zotero and am trying to perform some basic operations to help in management of group libraries.

Topics:

- Batch editing (say, replace USA with US or similar, in different fields)
- Statistics (say, numbers of records per collection, for all collection, for top/parent items only)
- Deletions (eg, remove all tags, used and unused)
- Usage (who modified what when)

A few complete examples would be very useful to many, as the main audience of Zotero are not necessarily programmers.

Thank you for considering.

**Comment by urschrei** [comment]
Unfortunately, I don't have time to write tutorials for the kind of issues you describe, although I'd be happy to look at pull requests if someone would like to submit them. More fundamentally, it sounds like what you describe is less about functionality specific to Pyzotero, and more about familiarity with Python and Zotero – the data structures returned by Pyzotero are well-documented and mostly self-describing, and interacting with the `write` API is also documented – I'd encourage you to explore things like collection statistics using something like Jupyter or iPython, and think about getting the answers you're looking for using methods and functions from the standard library. 
As for bulk editing, I suspect that will become easier when you're more familiar with Zotero's collection and item hierarchy; you'll have to retrieve the items or collections you'd like to edit, alter the dict items in question for each `Item` or `Collection`, then use either `update_items()` or `update_collections()` (new in v1.3.5) to bulk-upload your changes .
