### ISSUE TITLE
Trigger metadata retrieval when attaching PDFs

### ISSUE THREAD

**Issue by rageth** [urschrei/pyzotero#84]
# General
Platform:  Windows/MacOS
Python version:  2.7.15
Pyzotero version: 1.3.5

# Problem description
I'm writing a script to replicate a forrest of PDFs as a mirror network of links in Zotero. So far the system working well with a few test files. However, Zotero doesn't initiate an automatic metadata download when Pyzotero creates the link. Any idea how I might trigger metadata retrieval?

Thanks.

Gareth.

And thanks for pyzotero - it's a fantastic tool

**Comment by urschrei** [comment]
Do you mean creating a new item (i.e. a journal article) from a PDF that has been uploaded using the API? I don't think the API supports that functionality…

**Comment by rageth** [comment]
Thanks @urschrei, I had forgotten that the API works with the web based database and not the app directly. I'll work out another way of triggering this.

Thanks.

Gareth.
