### ISSUE TITLE
Can I Use Pyzotero On Zotero Standalone and Not Go Online? 

### ISSUE THREAD

**Issue by atanasj** [urschrei/pyzotero#86]
Hi,

Can you please tell me if I am able to use `Pyzotero`  on my local `Zotero` library without going online? 

I'm very new to `python`, so it may be an obvious answer---apologies of it is and I've missed it. 

I'm on a Mac using

```
osx Mojave
python 3.7
Atom IDE via hydrogen
```

Please let me know if you need any more information. 

Thanks in advance,
Atanas.

**Comment by urschrei** [comment]
No, Pyzotero only works with the web API, not with your local database.
