### ISSUE TITLE
Zotero.searches() not found

### ISSUE THREAD

**Issue by bjohas** [urschrei/pyzotero#91]
# General
Platform:  OS X 
Python version:  Python 3.6.4
Pyzotero version: latest

# Problem description

'Zotero' object has no attribute 'searches'

# If possible, paste the full traceback in a code block below, and fill in the summary

''Traceback (most recent call last):
  File "zapi.py", line 121, in <module>
    run()
  File "zapi.py", line 117, in run
    main(sys.argv[1:])
  File "zapi.py", line 110, in main
    zotero_searches(args.api_key, args.library_id, args.library_type)
  File "zapi.py", line 87, in zotero_searches
    items = zot.searches()
AttributeError: 'Zotero' object has no attribute 'searches'
''

**Comment by bjohas** [comment]
Other search methods do not work either - e.g. saved_search. What am I doing wrong?

**Comment by urschrei** [comment]
I can't reproduce this. Can you paste or link the complete script you're trying to use?

**Comment by bjohas** [comment]
See here: https://gist.github.com/bjohas/46231fa0a476c054617b91a1f12fc4d6

Run as:
> python3 searches.py API_KEY GROUP_LIB_ID

`
Traceback (most recent call last):
  File "searches.py", line 25, in <module>
    run()
  File "searches.py", line 21, in run
    main(sys.argv[1:])
  File "searches.py", line 18, in main
    zotero_searches(sys.argv[1], sys.argv[2], "group")
  File "searches.py", line 13, in zotero_searches
    items = zot.searches()
AttributeError: 'Zotero' object has no attribute 'searches'
`

I'm just starting to explore the library - many thanks for writing it, and apologies if this is my mistake!

**Comment by urschrei** [comment]
Hm. Can you confirm which version of Pyzotero you've installed? It should be `1.3.15`, and any version lower than `1.3.10` doesn't have saved-search functionality…

**Comment by bjohas** [comment]
Yep - that's the problem. I just did a pip install pyzotero (on OS X, 10.11.6) and it only gives me 1.3.7.:

> pip show pyzotero
> Name: Pyzotero
> Version: 1.3.7

I'll install directly from git!

**Comment by urschrei** [comment]
Hmm that's very odd – 1.3.15 is definitely available on PyPI, so pip should work just fine.

**Comment by bjohas** [comment]
I had installed a tool that somehow had 1.3.7 as requirement - hence that version was installed. I've now uninstalled that tool, and then uninstalled pyzotero, and reinstalled it: Now on 1.3.15. So that's all good.

However, with the same source as above, I now get:

> Traceback (most recent call last):
>   File "searches.py", line 9, in <module>
>    from pyzotero import zotero
> ImportError: cannot import name 'zotero'

**Comment by urschrei** [comment]
Can you verify that `import zotero` works in a bare python repl?

**Comment by bjohas** [comment]
Do you mean in the interpreter? 

> python3
> >>>...
> >>>import pyzotero 

works, but

> >>>from pyzotero import zotero

Thanks for the replies!

**Comment by urschrei** [comment]
There's almost certainly something wrong with your path or virtual environment:

    (venv) sth:~/dev/pztest $ python
    Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04) 
    [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from pyzotero import zotero
    >>> 

That's `3.1.15`, freshly installed from PyPI in a new virtualenv…

**Comment by bjohas** [comment]
THANK YOU! THANK YOU!
Yes, it was an issue with the path setting for python 3.6. Not sure why that happened, but it seems to work now!

**Comment by bjohas** [comment]
In case it's helpful to anybody else: Seems something was wrong with my python installation. In the end, I installed python3.7 from brew, installed pyzotero via pip and set the path in .profile to include /Library/Frameworks/Python.framework. Now everything works as advertised.
