### ISSUE TITLE
pyzotero is now packaged for conda @ conda-forge

### ISSUE THREAD

**Issue by moorepants** [urschrei/pyzotero#94]
FYI: https://github.com/conda-forge/pyzotero-feedstock

**Comment by urschrei** [comment]
Oh, delightful. I'll update the README and docs to let people know. Releases aren't super-frequent – is there a simple way of cutting new conda-forge releases in an automated fashion, or do you just watch the repo and update the build details at your end when necessary?

**Comment by moorepants** [comment]
If you release to PyPi a PR to conda forge will automatically be created. Would you like to be a maintainer on the conda forge feedstock?

**Comment by urschrei** [comment]
Oh, that's great. Not much point in making me a maintainer, I don't think – I don't use anaconda so I don't really know my way around its packaging system.

**Comment by moorepants** [comment]
Maintainer would just let you get notified of the recipe PRs and be able to merge them. It should be pretty seamless and simple for this package.

**Comment by urschrei** [comment]
Oh in that case, sure.

**Comment by moorepants** [comment]
done
