### ISSUE TITLE
self-assigned tag retrieval

### ISSUE THREAD

**Issue by floriandierickx** [urschrei/pyzotero#95]
# General
Platform:  OSX 10.14.4
Python version:  Python 3.6.8
Pyzotero version: pyzotero-1.3.15

# Problem description
It's a rather short question: is there a possibility to only retrieve self-assigned tags (without the automatic tags) ?

**Comment by urschrei** [comment]
By automatic tags, do you mean tags that are assigned e.g. when you add an item using the browser? Not as far as I know.

**Comment by floriandierickx** [comment]
I think automatic tags are the ones who get created indeed when you use the zotero browser addon (or maybe when retrieving through doi), but I rarely use them as they are too many to use in a practical way. That's why I was wondering if it's possible to retrieve a list of the tags that users assign themselves (excluding the automatic ones). I'm just starting to explore pyzotero (also with the aim of learning how to batch edit items), thanks for the development!
