### ISSUE TITLE
Case sensitive tag search queries?

### ISSUE THREAD

**Issue by TimBMK** [urschrei/pyzotero#97]
Platform:  Windows 10
Python version:  3.7.0
Pyzotero version: 1.3.15

Is it possible to do a case sensitive search query when filtering by tags? 

When retrieving items via the tag, the search query seems to be case insensitive. That is, for example:
zot.items(tag = "AGENCY")
zot.items(tag = "agency")
zot.items(tag = "Agency")
all produce the same result. 

Since I'm trying to specifically retrieve items via a case sensitive tag search (to replace them with proper case), it would be very helpful if there was a way to change that behaviour. I could not find any info on that in the Pyzotero or Zotero API docs. Am I missing something?

**Comment by urschrei** [comment]
Pyzotero doesn't modify the case of search input, so I _think_ it's the Zotero API that's ignoring case. Can you reproduce the problem using cURL? Try asking on the https://groups.google.com/forum/#!forum/zotero-dev if / when you have.

**Comment by TimBMK** [comment]
Yes, I was suspecting that. I think it's the way Zotero works with tags. I might try bringing it up there, thanks! Since it's a problem of computational efficiency and not code-breaking in my case, it might not be worth tinkering with the API itself though.
Thanks for the quick reply, and for the awesome Python package you made there! Makes my job cleaning up a couple hundred tags in a couple thousands entries so much easier.
